### ISSUE TITLE
Save state problem with Ink files

### ISSUE THREAD

**Issue by enderesting** [starmaid/augmented-gem#54]
Right now the save/load ink state system doesn't seem to be working...?
You can replicate the bug in `feature/scene-transition` branch, there's a scene transition from office to hallway. While saving does record global variable and state of the story in the json file, it's not translated back into the story after the transition (i checked by setting up the same knot in the next scene). When you save again from hallway to office, the previous save file is overwritten. 
The save/load calls are in `SceneTransition.cs`.
I also put a quick shortcut on the shelf so you can get the key easier without going through all the dialogue LOL

**Comment by starmaid** [comment]
in #62 I added a parameter in the inspector window "Load on start" which, when true, loads the save file (among other fixes that were preventing saves from working properly). This is true by default, and should be unchecked on the first level. This is a partial solution. 

The true solution may be creating a blank save on the home screen when selecting 'new game', and then having all levels load saves by default. Then we can handle multiple save files by renaming stuff and appending dates to things, autosaves, etc.
