### ISSUE TITLE
v0.0.2a Bugfixes

### ISSUE THREAD

**Issue by starmaid** [starmaid/augmented-gem#80]
List of things wrong with the 1a7c7749d773db6169ebde2692bac99c90b639a9 release. These are small fixes that are specific to this version, not larger issues that could be their own issue.

- [x] Collision on Statue
- [x] Gem Angry in hand sprite is blurry/sized wrong
- [x] Office music doesnt loop
- [x] StoryManager default text speed is not what buttons set in the 1_office instance
- [x] #83
- [x] #84
- [x] No hallway for demo, figure out where thank you text should go (see https://github.com/starmaid/augmented-gem/issues/80#issuecomment-1706114414)
- [x] Also maybe after thank you text it goes back to main menu? perhaps
- [x] Highlight overlapping with text makes some text difficult to read - potential fix would be to disable interact/transmute highlights entirely while in dialogue mode? Could also bring back the dimming effect on the textbox.
- [x] Also review guy said to improve how the highlights look. Idk this is not a bugfix anymore this is me leaving notes for star

**Comment by yoggypoggy** [comment]
Collision with statue doesnt work

**Comment by yoggypoggy** [comment]
Sprite issues (specifically this one, possibly more)
https://cdn.discordapp.com/attachments/1122687236467593336/1148521802952364032/image.png

**Comment by yoggypoggy** [comment]
Audio issues 
- office music doesnt loop
- office music's PlayOnAwake status can be controlled by the same function that starts the music
- add ambience to hallway

**Comment by yoggypoggy** [comment]
Text scrolling in the hallway is inconsistent with the office, this is due to buttons messing with the StoryManager's instance in the office instead of the prefab. she will resolve this via either a clean (work out prefabs properly) or dirty (change the settings in the hallway instance also lmao) implementation

**Comment by yoggypoggy** [comment]
Can't go from hallway back to office

**Comment by yoggypoggy** [comment]
After unlocking door, door cannot be walked through unless you move away/move back again

**Comment by yoggypoggy** [comment]
No hallway for demo, figure out where thank you text should go [this comment](https://github.com/starmaid/augmented-gem/issues/80#issuecomment-1706114414)

Also maybe after thank you text it goes back to main menu? perhaps

**Comment by yoggypoggy** [comment]
Highlight overlapping with text makes some text difficult to read - potential fix would be to disable interact/transmute highlights entirely while in dialogue mode?
![image](https://cdn.discordapp.com/attachments/1122687775213359224/1148520437148569660/image.png)
